### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Dhaulagiri** [Dhaulagiri/climbingnarc-videos#2]
This ticket is an overall road map for what I envision for this project.  Other ideas are always welcome.  

The overarching goal of this project is to build a much more responsive and interactive video browsing experience.  The main idea being that people like to watch climbing videos and I have a lot of videos in the archive now, so the easier we can make browsing and watching that archive the better.

I'm not sure how this will be deployed yet, but a drop in replacement for the current videos site - same urls - would be ideal.  For example, http://climbingnarc.com/videos/the-push-days-09-10/ would be intercepted by the Ember app instead of loading the wordpress page.

## Key items I would like to implement include:

- [ ] Index list of current videos (with thumbnails) that either has infinite scrolling to load additional videos or some sort of user directed action that can load additional videos.  There is some code in place for the latter but it is commented out at the moment.
- [ ] Video detail page that includes the video, comments, ratings and related videos.  
  - [ ] The comment part will require both the display of comments as well as allowing users to submit new comments
  - [ ] The most difficult of these is the ratings function which will require customization of the Wordpress API.  I would really like to keep this functionality though since rating videos allows for further categorization of videos based on their ratings.
- [ ] Video search to let users search generically as well as by specific climbers or climbing areas (each video is tagged through Wordpress's custom taxonomies with the climber(s) and climbing area(s) featured).  A basic version of this is implemented, but it would be much more powerful if we could filter on specific climbers/areas.
- [ ] The design in place right now is extremely basic.  I would like to come up with something much nicer.

## Open issues around these goals:

- [x] Embedding youtube/vimeo #3 
- [ ] Random video #4 
- [ ] Search #5 
- [ ] Filtering on taxonomies #6
- [ ] Show comments #7
- [ ] Show stars #8

**Comment by Dhaulagiri** [comment]
@xdumaine this issue outlines some of my ideas, but I'm pretty open to other ideas as well.

**Comment by Dhaulagiri** [comment]
If this project goes well I would consider porting the entire site over to Ember, so it's worth keeping that in mind as well.
